import { MenuItem, ComboItem, MenuPageReference } from '../types';

export const MENU_ITEMS: MenuItem[] = [
  // WAFFLES
  {
    id: 'waffle-1',
    name: 'Belgian Choco Waffle with Choice of Your Creamery',
    category: 'WAFFLES',
    price: 219,
    isVeg: true,
    isChefSpecial: true,
    isPopular: true,
    badge: 'Signature Cravings',
    description: 'Crisp golden Belgian waffle smothered with warm chocolate drizzle and served with your favorite gourmet creamery scoop.',
    imageUrl: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Belgian Choco Waffle with chocolate drizzle and ice cream',
  },
  {
    id: 'waffle-2',
    name: 'Red Velvet Waffle with Choice of Your Creamery',
    category: 'WAFFLES',
    price: 219,
    isVeg: true,
    isPopular: true,
    badge: 'Guest Favorite',
    description: 'Velvety crimson waffle paired with silky chocolate sauce and your choice of handcrafted ice cream creamery scoop.',
    imageUrl: 'https://images.unsplash.com/photo-1588785392665-f6d4a541417d?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Red Velvet Waffle with creamery scoop',
  },
  {
    id: 'waffle-3',
    name: 'Kiki Oreo Waffle with Choice of Your Creamery',
    category: 'WAFFLES',
    price: 219,
    isVeg: true,
    isChefSpecial: true,
    badge: 'Chef Pick',
    description: 'Crunchy crushed Oreo cookies over warm Belgian waffle with sweet cream and a scoop of rich artisanal creamery.',
    imageUrl: 'https://images.unsplash.com/photo-1598214886806-c87b84b7078b?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Kiki Oreo Waffle with cream and cookies',
  },
  {
    id: 'waffle-4',
    name: 'Coffee Mocha Waffle with Choice of Your Creamery',
    category: 'WAFFLES',
    price: 219,
    isVeg: true,
    description: 'Deep espresso-infused chocolate waffle served hot with cool creamy ice cream of your choice.',
    imageUrl: 'https://images.unsplash.com/photo-1504387828636-abeb50778c0c?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Coffee Mocha Waffle',
  },
  {
    id: 'waffle-5',
    name: 'Milk Choco Waffle with Choice of Your Creamery',
    category: 'WAFFLES',
    price: 219,
    isVeg: true,
    isPopular: true,
    description: 'Smooth melted milk chocolate poured across fresh waffle squares with your selected ice cream scoop.',
    imageUrl: 'https://images.unsplash.com/photo-1568051243851-f9b136146e97?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Milk Choco Waffle with creamery',
  },

  // CREAMERIES (Scoops / Cups / Cones)
  {
    id: 'cream-1',
    name: 'Biscoff Creamery',
    category: 'CREAMERIES',
    price: 109,
    isVeg: true,
    isChefSpecial: true,
    isPopular: true,
    badge: 'Bestseller',
    description: 'Signature spiced caramelized Lotus Biscoff swirl. *Waffle cone / cup: Rs. 10/- extra.',
    imageUrl: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Biscoff Ice Cream Scoop',
  },
  {
    id: 'cream-2',
    name: 'Belgian Chocolate Creamery',
    category: 'CREAMERIES',
    price: 109,
    isVeg: true,
    isPopular: true,
    description: 'Dark, velvety and deeply decadent Belgian cocoa creamery scoop. *Waffle cone / cup: Rs. 10/- extra.',
    imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Belgian Chocolate Ice Cream',
  },
  {
    id: 'cream-3',
    name: 'Alphonso Mango Creamery',
    category: 'CREAMERIES',
    price: 109,
    isVeg: true,
    description: 'Sun-ripened Alphonso mango pulp infused in velvety cream. *Waffle cone / cup: Rs. 10/- extra.',
    imageUrl: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Alphonso Mango Scoop',
  },
  {
    id: 'cream-4',
    name: 'Sitaphal & Jackfruit Creamery',
    category: 'CREAMERIES',
    price: 109,
    isVeg: true,
    badge: 'Regional Favorite',
    description: 'Exotic Indian custard apple & jackfruit hand-crafted creamery. *Waffle cone / cup: Rs. 10/- extra.',
    imageUrl: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Sitaphal Artisanal Scoop',
  },
  {
    id: 'cream-5',
    name: 'Red Velvet Cheese & Blueberry Cheese Creamery',
    category: 'CREAMERIES',
    price: 109,
    isVeg: true,
    description: 'Cream cheese base swirled with tart blueberry and red velvet crumble. *Waffle cone / cup: Rs. 10/- extra.',
    imageUrl: 'https://images.unsplash.com/photo-1560008511-11c63416e52d?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Berry Cheese Creamery',
  },
  {
    id: 'cream-6',
    name: 'Salted Caramel & Praline N Cream',
    category: 'CREAMERIES',
    price: 109,
    isVeg: true,
    isPopular: true,
    description: 'Buttery caramel ribbons with roasted praline nut bites. *Waffle cone / cup: Rs. 10/- extra.',
    imageUrl: 'https://images.unsplash.com/photo-1580915411954-282cb1b0d780?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Salted Caramel Creamery',
  },

  // THICK SHAKES
  {
    id: 'shake-1',
    name: 'Biscoff Thick Shake',
    category: 'THICK SHAKES',
    price: 209,
    isVeg: true,
    isChefSpecial: true,
    badge: 'House Special',
    description: 'Ultra-dense shake blended with generous speculoos cookies and caramelized Biscoff cream.',
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Biscoff Thick Shake with whipped cream',
  },
  {
    id: 'shake-2',
    name: 'Oreo Thick Shake',
    category: 'THICK SHAKES',
    price: 189,
    isVeg: true,
    isPopular: true,
    badge: 'Popular',
    description: 'Rich vanilla ice cream churned thick with chocolate cookies and dark chocolate drizzle.',
    imageUrl: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Oreo Thick Shake with chocolate sauce',
  },
  {
    id: 'shake-3',
    name: 'Kitkat Thick Shake',
    category: 'THICK SHAKES',
    price: 189,
    isVeg: true,
    description: 'Crisp wafer chocolate crunch blended into smooth creamy indulgence.',
    imageUrl: 'https://images.unsplash.com/photo-1553787499-6f9133860278?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Kitkat Shake',
  },
  {
    id: 'shake-4',
    name: 'Brownie Thick Shake',
    category: 'THICK SHAKES',
    price: 189,
    isVeg: true,
    isPopular: true,
    description: 'Chunks of warm fudge brownie whipped into thick chocolate shake.',
    imageUrl: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Brownie Thick Shake',
  },
  {
    id: 'shake-5',
    name: 'Mango / Strawberry / Black Current Shake',
    category: 'THICK SHAKES',
    price: 169,
    isVeg: true,
    description: 'Real fruit purée blended with chilled creamery milk. Available in Mango, Strawberry, and Black Current.',
    imageUrl: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Fruit Shakes',
  },

  // MOCKTAILS
  {
    id: 'mock-1',
    name: 'Blue Curaçao Mocktail',
    category: 'MOCKTAILS',
    price: 89,
    isVeg: true,
    isPopular: true,
    badge: 'Refreshing',
    description: 'Cool citrus curacao sparkler served over crushed ice with fresh lime wedges and mint.',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Blue Curacao Mocktail',
  },
  {
    id: 'mock-2',
    name: 'Mint Mojito',
    category: 'MOCKTAILS',
    price: 89,
    isVeg: true,
    isPopular: true,
    description: 'Fresh garden mint muddled with tart lime juice and effervescent sparkling soda.',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Mint Mojito Mocktail',
  },
  {
    id: 'mock-3',
    name: 'Kiwi Mojito',
    category: 'MOCKTAILS',
    price: 99,
    isVeg: true,
    description: 'Tangy fresh kiwi extract combined with crushed mint and bubbly fizz.',
    imageUrl: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Kiwi Mojito',
  },
  {
    id: 'mock-4',
    name: 'Strawberry Splash & Green Apple',
    category: 'MOCKTAILS',
    price: 89,
    isVeg: true,
    description: 'Crisp green apple and juicy strawberry cooler with fizzy soda.',
    imageUrl: 'https://images.unsplash.com/photo-1587888637140-849b25d80ef9?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Strawberry Splash Mocktail',
  },

  // COMBOS
  {
    id: 'combo-1',
    name: 'Veg Burger Combo',
    category: 'COMBOS',
    price: 249,
    isVeg: true,
    badge: 'Popular Value',
    description: 'Veg Burger (Your Choice) + French Fries (Your Choice) + Mojito (Blue Curaçao / Mint).',
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Veg Burger Combo with fries and drink',
  },
  {
    id: 'combo-2',
    name: 'Non Veg Burger Combo',
    category: 'COMBOS',
    price: 259,
    isVeg: false,
    badge: 'Top Pick',
    description: 'Chicken Burger (Your Choice) + French Fries (Your Choice) + Mojito (Blue Curaçao / Mint).',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Non Veg Burger Combo',
  },
  {
    id: 'combo-3',
    name: 'Veg Sandwich Combo',
    category: 'COMBOS',
    price: 229,
    isVeg: true,
    description: 'Grilled Sandwich (Your Choice) + French Fries (Your Choice) + Soft Drink.',
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Veg Sandwich Combo',
  },
  {
    id: 'combo-4',
    name: 'Non Veg Sandwich Combo',
    category: 'COMBOS',
    price: 259,
    isVeg: false,
    description: 'Grilled Chicken Sandwich (Your Choice) + French Fries (Your Choice) + Soft Drink.',
    imageUrl: 'https://images.unsplash.com/photo-1621800043295-a73fe2f76e2c?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Non Veg Sandwich Combo',
  },
  {
    id: 'combo-5',
    name: 'Veg Fried Rice / Noodles Combo',
    category: 'COMBOS',
    price: 259,
    isVeg: true,
    description: 'Choice of Veg Fried Rice or Noodles + Veg Manchuria (Wet/Dry) + Soft Drink.',
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Veg Fried Rice Combo',
  },
  {
    id: 'combo-6',
    name: 'Chef Special Chicken Fried Rice / Noodles Combo',
    category: 'COMBOS',
    price: 359,
    isVeg: false,
    isChefSpecial: true,
    badge: 'Chef Choice',
    description: 'Chef Special Chicken Fried Rice or Noodles + Garlic Chicken / Chilli Egg + Soft Drink.',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Chef Special Chicken Rice Combo',
  },

  // CREAMY BREADS & BURGERS
  {
    id: 'bread-1',
    name: 'Cheese Blast Veg Burger',
    category: 'CREAMY BREADS',
    price: 149,
    isVeg: true,
    isChefSpecial: true,
    badge: 'Cheese Blast',
    description: 'Crispy patty overflowing with molten hot cheese, fresh lettuce and creamy signature sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Cheese Blast Veg Burger',
  },
  {
    id: 'bread-2',
    name: 'Cheese Blast Chicken Burger',
    category: 'CREAMY BREADS',
    price: 149,
    isVeg: false,
    isChefSpecial: true,
    badge: 'Signature',
    description: 'Juicy spiced chicken patty loaded with a molten cheese center and toasted brioche buns.',
    imageUrl: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Cheese Blast Chicken Burger',
  },
  {
    id: 'bread-3',
    name: 'Paneer & Corn Sandwiches',
    category: 'CREAMY BREADS',
    price: 129,
    isVeg: true,
    description: 'Golden grilled sandwich stuffed with seasoned spiced paneer, sweet corn and creamy spread. *Extra cheese: Rs. 15/-.',
    imageUrl: 'https://images.unsplash.com/photo-1554433607-66b5efe9d304?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Paneer Sandwich',
  },
  {
    id: 'bread-4',
    name: 'Chicken Tikka Sandwich',
    category: 'CREAMY BREADS',
    price: 149,
    isVeg: false,
    isChefSpecial: true,
    description: 'Smoky chicken tikka chunks grilled with herb butter and melted cheese.',
    imageUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Chicken Tikka Sandwich',
  },
  {
    id: 'bread-5',
    name: 'Peri Peri Burger (Veg / Chicken)',
    category: 'CREAMY BREADS',
    price: 129,
    isVeg: true,
    description: 'Zesty peri peri seasoning infused patty with crisp onions, lettuce, and mayo.',
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Peri Peri Burger',
  },

  // FRIED ITEMS
  {
    id: 'fried-1',
    name: 'Peri Peri & Chilli Lemon Fries',
    category: 'FRIED ITEMS',
    price: 109,
    isVeg: true,
    isPopular: true,
    badge: 'Crispy Snack',
    description: 'Crispy golden potato fries tossed in tangy chilli lemon or spicy peri-peri dust.',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Seasoned French Fries',
  },
  {
    id: 'fried-2',
    name: 'Chicken Pop Corn',
    category: 'FRIED ITEMS',
    price: 170,
    isVeg: false,
    isPopular: true,
    badge: 'Crispy Favorite',
    description: 'Crunchy bite-sized marinated chicken tenders served with dips.',
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Chicken Popcorn',
  },
  {
    id: 'fried-3',
    name: 'Chicken Fried Wings (6 Pcs)',
    category: 'FRIED ITEMS',
    price: 239,
    isVeg: false,
    badge: 'Party Starter',
    description: 'Six juicy fried wings with crispy golden batter and dipping sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1527477321016-c567bb0473b6?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Crispy Fried Chicken Wings',
  },
  {
    id: 'fried-4',
    name: 'Spring Potato & Peri Peri Spring Potato',
    category: 'FRIED ITEMS',
    price: 119,
    isVeg: true,
    description: 'Spiral-cut potato skewer deep-fried to crispy perfection with peri peri masala.',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281692?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Tornado Spring Potato',
  },

  // CREAMY PASTA
  {
    id: 'pasta-1',
    name: 'White Creamy Veg Pasta',
    category: 'CREAMY PASTA',
    price: 219,
    isVeg: true,
    isPopular: true,
    description: 'Tender penne tossed in rich garlic parmesan cream sauce with garden vegetables.',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281692?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'White Creamy Alfredo Pasta',
  },
  {
    id: 'pasta-2',
    name: 'Pink Veg Pasta & Veg Mix Sauce Pasta',
    category: 'CREAMY PASTA',
    price: 219,
    isVeg: true,
    isChefSpecial: true,
    badge: 'Chef Special',
    description: 'A harmonious blend of tangy tomato pomodoro and velvety cream cheese sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Pink Mix Sauce Pasta',
  },
  {
    id: 'pasta-3',
    name: 'Creamy White Chicken Pasta',
    category: 'CREAMY PASTA',
    price: 259,
    isVeg: false,
    isPopular: true,
    description: 'Sautéed tender chicken breast strips in rich garlic cream sauce over penne.',
    imageUrl: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Chicken White Creamy Pasta',
  },

  // MOMOS
  {
    id: 'momo-1',
    name: 'Veg Momos (Steamed / Fried)',
    category: 'MOMOS',
    price: 129,
    isVeg: true,
    description: 'Delicate handmade dumplings filled with finely chopped seasoned vegetables and fiery red sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Steamed Veg Momos',
  },
  {
    id: 'momo-2',
    name: 'Paneer Momos (Steamed / Fried)',
    category: 'MOMOS',
    price: 149,
    isVeg: true,
    description: 'Stuffed with soft shredded cottage cheese, fresh coriander, and spices.',
    imageUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Paneer Momos',
  },
  {
    id: 'momo-3',
    name: 'Chicken Momos (Steamed / Fried)',
    category: 'MOMOS',
    price: 149,
    isVeg: false,
    isPopular: true,
    badge: 'Popular',
    description: 'Juicy minced spiced chicken steamed or flash-fried to golden crispiness.',
    imageUrl: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Chicken Momos',
  },

  // NOODLES & RICE
  {
    id: 'rice-1',
    name: 'Chef Special Noodles (Veg / Chicken)',
    category: 'NOODLES & RICE',
    price: 199,
    isVeg: true,
    isChefSpecial: true,
    badge: 'Chef Special',
    description: 'Wok-tossed noodles with exotic vegetables and chef special secret sauce blend.',
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Chef Special Noodles',
  },
  {
    id: 'rice-2',
    name: 'Juicy Manchurian Fried Rice',
    category: 'NOODLES & RICE',
    price: 179,
    isVeg: true,
    isPopular: true,
    description: 'Aromatic fried rice layered with juicy Manchurian gravy balls and spring onions.',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Manchurian Fried Rice',
  },
  {
    id: 'rice-3',
    name: 'Double Egg Chicken Fried Rice',
    category: 'NOODLES & RICE',
    price: 189,
    isVeg: false,
    description: 'High-heat wok fried rice with double egg scramble and tender chicken chunks.',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Chicken Fried Rice',
  },

  // SOUPS & STARTERS
  {
    id: 'starter-1',
    name: 'Chicken Chilly Lollipop (6 Pcs)',
    category: 'SOUPS & STARTERS',
    price: 260,
    isVeg: false,
    isChefSpecial: true,
    badge: 'Crowd Pleaser',
    description: '6 pieces of succulent chicken drummettes tossed in spicy Indo-Chinese chilli glaze.',
    imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Chicken Chilly Lollipop',
  },
  {
    id: 'starter-2',
    name: 'Paneer 65 & Chilli Paneer',
    category: 'SOUPS & STARTERS',
    price: 189,
    isVeg: true,
    isPopular: true,
    description: 'Crispy batter-fried cottage cheese cubes tempered with curry leaves and green chillies.',
    imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Paneer 65 Starter',
  },
  {
    id: 'starter-3',
    name: 'Chicken Manchow Soup & Veg Manchow',
    category: 'SOUPS & STARTERS',
    price: 169,
    isVeg: false,
    description: 'Hearty dark broth loaded with minced chicken, garlic, cilantro and topped with crispy noodles.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Hot Manchow Soup',
  },
];

// All 29 Artisanal Creameries flavours confirmed on the menu
export const CREAMERIES_LIST = [
  'Alphonso Mango',
  'Anjeer Almond',
  'Belgian Chocolate',
  'Biscoff',
  'Blackcurrant',
  'Blue Angel',
  'Blueberry',
  'Blueberry Cheese',
  'Butterscotch',
  'Chikku',
  'Cookies N Cream',
  'Cranberry Red Velvet',
  'French Vanilla',
  'Gajar Halwa',
  'Jackfruit',
  'Jamun',
  'Litchi',
  'Muskmelon',
  'Oreo',
  'Pineapple',
  'Praline N Cream',
  'Raj Bogh',
  'Red Velvet Cheese',
  'Salted Caramel',
  'Sitaphal',
  'Spicy Guava',
  'Strawberry',
  'Swiss Chocolate',
  'Tender Coconut',
];

// Reference metadata for the 7 original restaurant menu pages
export const ORIGINAL_MENU_PAGES: MenuPageReference[] = [
  {
    id: 1,
    title: 'Waffle with Creameries & Creameries',
    subtitle: 'Page 4 • Authentic Dessert Sheet',
    sections: ['Belgian Choco Waffle (219)', 'Red Velvet (219)', 'Kiki Oreo (219)', 'Coffee Mocha (219)', 'Milk Choco (219)', '29 Handcrafted Creameries (109 each)'],
    description: 'The heart of Creamy Waffles. Freshly pressed Belgian waffles served with choices of 29 artisanal creamery scoops.',
    highlights: ['Choice of creamery included with waffles', 'Waffle Cone / Waffle Cup: Rs. 10/- extra', 'Biscoff, Sitaphal, Belgian Choco favorites'],
  },
  {
    id: 2,
    title: 'Creamy Pasta, Mocktails & Thick Shakes',
    subtitle: 'Page 5 • Indulgent Drinks & Italian',
    sections: ['Creamy Pastas (White, Pink, Mix, Red Sauce)', 'Mocktails (Blue Curaçao, Mojitos, Splash)', 'Thick Shakes (Oreo, Biscoff, Kitkat, Brownie)'],
    description: 'Hand-blended rich thick shakes, refreshing fizzy mocktails, and rich penne pasta.',
    highlights: ['Biscoff Thick Shake: Rs. 209/-', 'Blue Curaçao: Rs. 89/-', 'Creamy Chicken & Veg Pastas: Rs. 219 - 259/-'],
  },
  {
    id: 3,
    title: 'Creamy Breads & Fried Items',
    subtitle: 'Page 3 • Burgers, Sandwiches & Crispy Sides',
    sections: ['Veg Burgers & Sandwiches', 'Non-Veg Burgers & Sandwiches', 'Fried Items (Fries, Nuggets, Popcorn, Spring Potato)'],
    description: 'Hot grilled sandwiches, cheese blast burgers, crispy potato wedges and chicken popcorn.',
    highlights: ['Extra Cheese: Rs. 15/-', 'Cheese Blast Chicken Burger: Rs. 149/-', 'Spring Potato: Rs. 119/-'],
  },
  {
    id: 4,
    title: 'Value Combos',
    subtitle: 'Page 6 • Meals with Drinks & Fries',
    sections: ['Burger Combos (Rs. 249 / 259)', 'Sandwich Combos (Rs. 229 / 259)', 'Rice & Noodles Combos (Rs. 259 / 279 / 339 / 359)'],
    description: 'Perfect combinations including burgers/sandwiches/noodles with french fries, Manchuria, and soft drinks or mojitos.',
    highlights: ['Best value sets for dining-in and takeaway', 'Includes choice of fries & beverage'],
  },
  {
    id: 5,
    title: 'Noodles & Rice Bowl',
    subtitle: 'Page 1 • Chinese & Indo-Asian Wok',
    sections: ['Veg Noodles & Non-Veg Noodles', 'Veg Fried Rice & Non-Veg Fried Rice', 'Chef Special Noodles (199 / 209)'],
    description: 'Sizzling wok-prepared noodles and fried rice with egg, paneer, mushroom, and chicken.',
    highlights: ['Packaging Rs. 10/- extra', 'Manchurian & Schezwan varieties'],
  },
  {
    id: 6,
    title: 'Soups, Salads & Starters',
    subtitle: 'Page 2 • Appetizers & Sizzlers',
    sections: ['Healthy Salads & Soups', 'Veg Starters (Manchurian, 65, Chilli Paneer)', 'Non-Veg Starters (Wings, Lollipops, Chilli Chicken)'],
    description: 'Crispy starters including Chicken Chilly Lollipop-6 Pcs, Paneer 65, and comforting soups.',
    highlights: ['Chicken Chilly Lollipop-6 Pcs: Rs. 260/-', 'Wet & Dry Manchurian options'],
  },
  {
    id: 7,
    title: 'Momos & Beverages',
    subtitle: 'Page 7 • Dumplings & Hydration',
    sections: ['Steamed Momos (Veg, Paneer, Chicken)', 'Fried Momos (Veg, Paneer, Chicken)', 'Water, Buttermilk & Soft Drinks'],
    description: 'Tender steamed and crispy fried Himalayan-style dumplings paired with chilled beverages.',
    highlights: ['Steamed & Fried Momos: Rs. 129 - 149/-', 'Mineral water & refreshing buttermilk: Rs. 10 - 60/-'],
  },
];
